# Generated by Django 3.0.7 on 2020-07-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='lenght1',
            new_name='lenght',
        ),
    ]
