# Generated by Django 3.0.7 on 2020-07-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_auto_20200729_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
