# Generated by Django 3.0.7 on 2020-08-01 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_cinema'),
    ]

    operations = [
        migrations.CreateModel(
            name='showTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('price', models.IntegerField()),
                ('saleble_seats', models.IntegerField()),
                ('free_seats', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'فروش آغاز نشده'), (2, 'درحال فروش بلیط'), (3, 'بلیط ها تمام شد'), (4, 'فروش بلیط بسته شد'), (5, 'فیلم پخش شد'), (6, 'سانس لغو شد')])),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.Cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.Movie')),
            ],
        ),
    ]
